export const GET_CITY_NAME = 'GET_CITY_NAME';

export const FETCH_WEATHER = 'FETCH_WEATHER_API_DATA';
export const FETCH_WEATHER_REJECTED = 'FETCH_WEATHER_REJECTED';
export const FETCHING_WEATHER_FULFILLED = 'FETCHING_WEATHER_FULFILLED';